# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pymysql
from PyQt5 import QtCore, QtGui, QtWidgets

data_ID, data_PW = "",""
sql = ""

conn = pymysql.connect(host='127.0.0.1', user='root', passwd='dlshfl^^7850', db='myDB', charset='utf8')
cur = conn.cursor()

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 761, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("휴먼매직체")
        font.setPointSize(22)
        self.label_title.setFont(font)
        self.label_title.setToolTipDuration(3)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 330, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(684, 520, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 240, 56, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 270, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Edit_ID = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_ID.setGeometry(QtCore.QRect(350, 240, 113, 20))
        self.Edit_ID.setObjectName("Edit_ID")
        self.Edit_PW = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_PW.setGeometry(QtCore.QRect(350, 270, 113, 20))
        self.Edit_PW.setObjectName("Edit_PW")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.login) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.makeAccount) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "오늘의 의상은?"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "+New Account"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "Password"))

    def login(self):
        data_ID = self.Edit_ID.text()
        data_PW = self.Edit_PW.text()
        
        cur.execute("select * from userTABLE")

        while(True):
            row = cur.fetchone()
            if row == None:
                break
            if data_ID == row[0] and data_PW == row[1]:
                print("success")

    def makeAccount(self):
        data_ID = self.Edit_ID.text()
        data_PW = self.Edit_PW.text()
        data3 = self.Edit_ID.text()
        data4 = '1885'

        sql = "insert into userTABLE values('" + data_ID + "','" + data_PW + "','" + data3 + "'," + data3 + ")"
        cur.execute(sql)
        conn.commit()
        conn.close()

