# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pymysql
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineEdit_inputID = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_inputID.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.lineEdit_inputID.setObjectName("lineEdit_inputID")
        self.lineEdit_inputPW = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_inputPW.setGeometry(QtCore.QRect(100, 50, 113, 20))
        self.lineEdit_inputPW.setObjectName("lineEdit_inputPW")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 30, 56, 12))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 56, 12))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_PNumber = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_PNumber.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.lineEdit_PNumber.setObjectName("lineEdit_PNumber")
        self.Create = QtWidgets.QPushButton(Dialog)
        self.Create.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.Create.setObjectName("Create")
        self.Cancel = QtWidgets.QPushButton(Dialog)
        self.Cancel.setGeometry(QtCore.QRect(280, 50, 75, 23))
        self.Cancel.setObjectName("Cancel")

        self.retranslateUi(Dialog)
        self.Create.clicked.connect(Dialog.createNewAccount) # type: ignore
        self.Cancel.clicked.connect(Dialog.cancel) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ID"))
        self.label_2.setText(_translate("Dialog", "PW"))
        self.label_3.setText(_translate("Dialog", "Phone Num"))
        self.Create.setText(_translate("Dialog", "create"))
        self.Cancel.setText(_translate("Dialog", "cancel"))

    def createNewAccount(self):
        conn, cur = None, None
        inputNewID, inputNewPW, inputNewPNumber = "","",""
        sql = ""

        conn = pymysql.connect(host='127.0.0.1', user='root', passwd='dlshfl^^7850', db='myDB', charset='utf8')
        cur = conn.cursor()
        sql = "CREATE TABLE IF NOT EXISTS userData (id char(10), pw char(15), pNumber int)"
        cur.execute(sql)

        inputNewID = self.lineEdit_inputID.text()
        inputNewPW = self.lineEdit_inputPW.text()
        inputNewPNumber = self.lineEdit_PNumber.text()

        sql = "INSERT INTO userData VALUES('" + inputNewID + "','" + inputNewPW + "'," + inputNewPNumber + ")"
        cur.execute(sql)

        conn.commit()
        conn.close()