# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

isLogin = False
returnID = ""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 216)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 20, 56, 12))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_ID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ID.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.lineEdit_PW = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PW.setGeometry(QtCore.QRect(100, 90, 113, 20))
        self.lineEdit_PW.setObjectName("lineEdit_PW")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 56, 12))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 56, 12))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(230, 60, 75, 23))
        self.loginBtn.setObjectName("loginBtn")
        self.NewAccountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NewAccountBtn.setGeometry(QtCore.QRect(230, 90, 75, 23))
        self.NewAccountBtn.setObjectName("NewAccountBtn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 56, 12))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(100, 120, 201, 41))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.loginBtn.clicked.connect(MainWindow.login) # type: ignore
        self.NewAccountBtn.clicked.connect(MainWindow.createNewAccount) # type: ignore
        self.loginBtn.clicked.connect(MainWindow.changeWindow) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "ID"))
        self.label_3.setText(_translate("MainWindow", "PW"))
        self.loginBtn.setText(_translate("MainWindow", "Sign In"))
        self.NewAccountBtn.setText(_translate("MainWindow", "New"))
        self.label_4.setText(_translate("MainWindow", "State"))

    def login(self):
        inputID, inputPW = "",""

        conn = pymysql.connect(host='127.0.0.1', user='root', passwd='dlshfl^^7850', db='myDB', charset='utf8')
        cur = conn.cursor()
        cur.execute("select * from userData")

        inputID = self.lineEdit_ID.text()
        inputPW = self.lineEdit_PW.text()

        
        while(True):
            row = cur.fetchone()
            if row == None:
                break
            self.textEdit.clear()
            if inputID == row[0] and inputPW == row[1]:
                print("success")
                self.textEdit.append("login success")
                self.textEdit.append("어서오세요" + inputID + "님")
                returnID = inputID
                self.loginBtn.setEnabled(False)
            else:
                self.textEdit.append("login fail")
            