# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recommand.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1031, 585)
        font = QtGui.QFont()
        font.setFamily("서울남산 장체B")
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(870, 50, 121, 25))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_Closet = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_Closet.setObjectName("btn_Closet")
        self.verticalLayout_4.addWidget(self.btn_Closet)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 10, 221, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdTemp = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdTemp.setObjectName("lcdTemp")
        self.verticalLayout.addWidget(self.lcdTemp)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(540, 140, 451, 181))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_down = QtWidgets.QTableWidget(self.horizontalLayoutWidget_3)
        self.tableWidget_down.setAlternatingRowColors(True)
        self.tableWidget_down.setRowCount(20)
        self.tableWidget_down.setColumnCount(4)
        column_headers = ['브랜드', '상하의', '색상', '소매']
        self.tableWidget_down.setHorizontalHeaderLabels(column_headers)
        self.tableWidget_down.setObjectName("tableWidget_down")
        self.horizontalLayout_3.addWidget(self.tableWidget_down)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 360, 451, 191))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_out = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget_out.setAlternatingRowColors(True)
        self.tableWidget_out.setRowCount(20)
        self.tableWidget_out.setColumnCount(4)
        column_headers = ['브랜드', '상하의', '색상', '소매']
        self.tableWidget_out.setHorizontalHeaderLabels(column_headers)
        self.tableWidget_out.setObjectName("tableWidget_out")
        self.horizontalLayout_2.addWidget(self.tableWidget_out)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 140, 451, 181))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_up = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget_up.setAlternatingRowColors(True)
        self.tableWidget_up.setRowCount(20)
        self.tableWidget_up.setColumnCount(4)
        column_headers = ['브랜드', '상하의', '색상', '소매']
        self.tableWidget_up.setHorizontalHeaderLabels(column_headers)
        self.tableWidget_up.setObjectName("tableWidget_up")
        self.horizontalLayout.addWidget(self.tableWidget_up)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(870, 20, 121, 25))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_LogOut = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_LogOut.setObjectName("btn_LogOut")
        self.verticalLayout_3.addWidget(self.btn_LogOut)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 120, 56, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(540, 120, 56, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 340, 56, 12))
        self.label_3.setObjectName("label_3")
        self.btn_Recommand = QtWidgets.QPushButton(Dialog)
        self.btn_Recommand.setGeometry(QtCore.QRect(700, 460, 289, 91))
        font = QtGui.QFont()
        font.setFamily("휴먼엑스포")
        font.setPointSize(26)
        self.btn_Recommand.setFont(font)
        self.btn_Recommand.setObjectName("btn_Recommand")

        self.retranslateUi(Dialog)
        self.btn_LogOut.clicked.connect(Dialog.CS_logOut) # type: ignore
        self.btn_Closet.clicked.connect(Dialog.CS_myCloset) # type: ignore
        self.btn_Recommand.clicked.connect(Dialog.recommand) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_Closet.setText(_translate("Dialog", "My Closet"))
        self.btn_LogOut.setText(_translate("Dialog", "Log Out"))
        self.label.setText(_translate("Dialog", "상의"))
        self.label_2.setText(_translate("Dialog", "하의"))
        self.label_3.setText(_translate("Dialog", "겉옷"))
        self.btn_Recommand.setText(_translate("Dialog", "추천해줘!"))
