# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recommand.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(795, 558)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(630, 40, 121, 25))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_Closet = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_Closet.setObjectName("btn_Closet")
        self.verticalLayout_4.addWidget(self.btn_Closet)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 10, 221, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdTemp = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdTemp.setObjectName("lcdTemp")
        self.verticalLayout.addWidget(self.lcdTemp)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 510, 771, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_Recommand = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_Recommand.setObjectName("btn_Recommand")
        self.verticalLayout_2.addWidget(self.btn_Recommand)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(530, 120, 221, 371))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit_Out = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.textEdit_Out.setObjectName("textEdit_Out")
        self.horizontalLayout_3.addWidget(self.textEdit_Out)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(290, 120, 221, 371))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_Down = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEdit_Down.setObjectName("textEdit_Down")
        self.horizontalLayout_2.addWidget(self.textEdit_Down)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 120, 221, 371))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_Up = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_Up.setObjectName("textEdit_Up")
        self.horizontalLayout.addWidget(self.textEdit_Up)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(630, 10, 121, 25))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_LogOut = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_LogOut.setObjectName("btn_LogOut")
        self.verticalLayout_3.addWidget(self.btn_LogOut)

        self.retranslateUi(Dialog)
        self.btn_LogOut.clicked.connect(Dialog.CS_logOut) # type: ignore
        self.btn_Closet.clicked.connect(Dialog.CS_myCloset) # type: ignore
        self.btn_Recommand.clicked.connect(Dialog.recommand) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_Closet.setText(_translate("Dialog", "My Closet"))
        self.btn_Recommand.setText(_translate("Dialog", "Recommand"))
        self.btn_LogOut.setText(_translate("Dialog", "Log Out"))
